# Purpose: Seed the database with some initial data
# Before running the seed lets make sure we have a clean database

# First lets delete all the data in the database
Interest.destroy_all
Category.destroy_all

# Lets set the index back to 1
ActiveRecord::Base.connection.reset_pk_sequence!('categories')
ActiveRecord::Base.connection.reset_pk_sequence!('interests')

# First lets create some categories
Category.create(name: 'Music')
Category.create(name: 'Bussiness')
Category.create(name: 'Food & Drink')
Category.create(name: 'Community')
Category.create(name: 'Arts')
Category.create(name: 'Film & Media')
Category.create(name: 'Sports & Fitness')
Category.create(name: 'Health')
Category.create(name: 'Science & Tech')
Category.create(name: 'Travel & Outdoor')
Category.create(name: 'Charity & Causes')
Category.create(name: 'Spirituality')
Category.create(name: 'Family & Education')
Category.create(name: 'Holiday')
Category.create(name: 'Government')
Category.create(name: 'Fashion')
Category.create(name: 'Home & Lifestyle')
Category.create(name: 'Auto, Boat & Air')
Category.create(name: 'Hobbies')
Category.create(name: 'School Activities')

# Now lets create some interests for the music category
Interest.create(name: 'Alternative', category_id: 1)
Interest.create(name: 'Blues & Jazz', category_id: 1)
Interest.create(name: 'Classical', category_id: 1)
Interest.create(name: 'Country', category_id: 1)
Interest.create(name: 'Cultural', category_id: 1)
Interest.create(name: 'EDM/Electronic', category_id: 1)
Interest.create(name: 'Folk', category_id: 1)
Interest.create(name: 'Hip Hop/Rap', category_id: 1)
Interest.create(name: 'Indie', category_id: 1)
Interest.create(name: 'Latin', category_id: 1)
Interest.create(name: 'Metal', category_id: 1)
Interest.create(name: 'Opera', category_id: 1)
Interest.create(name: 'Pop', category_id: 1)
Interest.create(name: 'R&B', category_id: 1)
Interest.create(name: 'Reggae', category_id: 1)
Interest.create(name: 'Religious/Spiritual', category_id: 1)
Interest.create(name: 'Rock', category_id: 1)
Interest.create(name: 'Top 40', category_id: 1)
Interest.create(name: 'Acoustic', category_id: 1)
Interest.create(name: 'Americana', category_id: 1)
Interest.create(name: 'Bluegrass', category_id: 1)
Interest.create(name: 'Blues', category_id: 1)
Interest.create(name: 'Dj/Dance', category_id: 1)
Interest.create(name: 'EDM', category_id: 1)
Interest.create(name: 'Electronic', category_id: 1)
Interest.create(name: 'Experimental', category_id: 1)
Interest.create(name: 'Jazz', category_id: 1)
Interest.create(name: 'Psychedelic', category_id: 1)
Interest.create(name: 'Punk/Harcore', category_id: 1)
Interest.create(name: 'Singer/Songwriter', category_id: 1)
Interest.create(name: 'World', category_id: 1)
Interest.create(name: 'Other', category_id: 1)

# Now lets create some interests for the bussiness category
Interest.create(name: 'Startups & Small Business', category_id: 2)
Interest.create(name: 'Finance', category_id: 2)
Interest.create(name: 'Environment & Sustainability', category_id: 2)
Interest.create(name: 'Educators', category_id: 2)
Interest.create(name: 'Real Estate', category_id: 2)
Interest.create(name: 'Non Profits & NGOs', category_id: 2)
Interest.create(name: 'Sales & Marketing', category_id: 2)
Interest.create(name: 'Media', category_id: 2)
Interest.create(name: 'Design', category_id: 2)
Interest.create(name: 'Career', category_id: 2)
Interest.create(name: 'Investment', category_id: 2)
Interest.create(name: 'Other', category_id: 2)

# Now lets create some interests for the food & drink category
Interest.create(name: 'Beer', category_id: 3)
Interest.create(name: 'Wine', category_id: 3)
Interest.create(name: 'Food', category_id: 3)
Interest.create(name: 'Spirits', category_id: 3)
Interest.create(name: 'Other', category_id: 3)

# Now lets create some interests for the community category
Interest.create(name: 'State', category_id: 4)
Interest.create(name: 'Country', category_id: 4)
Interest.create(name: 'City/Town', category_id: 4)
Interest.create(name: 'LGBTQ+', category_id: 4)
Interest.create(name: 'Medieval', category_id: 4)
Interest.create(name: 'Renaissance', category_id: 4)
Interest.create(name: 'Heritage', category_id: 4)
Interest.create(name: 'Nationality', category_id: 4)
Interest.create(name: 'Language', category_id: 4)
Interest.create(name: 'Historic', category_id: 4)
Interest.create(name: 'Other', category_id: 4)

# Now lets create some interests for the arts category
Interest.create(name: 'Theatre', category_id: 5)
Interest.create(name: 'Musical', category_id: 5)
Interest.create(name: 'Ballet', category_id: 5)
Interest.create(name: 'Dance', category_id: 5)
Interest.create(name: 'Opera', category_id: 5)
Interest.create(name: 'Orchestra', category_id: 5)
Interest.create(name: 'Craft', category_id: 5)
Interest.create(name: 'Fine Art', category_id: 5)
Interest.create(name: 'Literary Arts', category_id: 5)
Interest.create(name: 'Comedy', category_id: 5)
Interest.create(name: 'Sculpture', category_id: 5)
Interest.create(name: 'Painting', category_id: 5)
Interest.create(name: 'Design', category_id: 5)
Interest.create(name: 'Jewelry', category_id: 5)
Interest.create(name: 'Other', category_id: 5)

# Now lets create some interests for the film & media category
Interest.create(name: 'TV', category_id: 6)
Interest.create(name: 'Film', category_id: 6)
Interest.create(name: 'Anime', category_id: 6)
Interest.create(name: 'Gaming', category_id: 6)
Interest.create(name: 'Comics', category_id: 6)
Interest.create(name: 'Adult', category_id: 6)
Interest.create(name: 'Comedy', category_id: 6)
Interest.create(name: 'Other', category_id: 6)

# Now lets create some interests for the sports & fitness category
Interest.create(name: 'Running', category_id: 7)
Interest.create(name: 'Walking', category_id: 7)
Interest.create(name: 'Cycling', category_id: 7)
Interest.create(name: 'Mountain Biking', category_id: 7)
Interest.create(name: 'Obstacles', category_id: 7)
Interest.create(name: 'Basketball', category_id: 7)
Interest.create(name: 'Football', category_id: 7)
Interest.create(name: 'Baseball', category_id: 7)
Interest.create(name: 'Soccer', category_id: 7)
Interest.create(name: 'Golf', category_id: 7)
Interest.create(name: 'Volleyball', category_id: 7)
Interest.create(name: 'Tennis', category_id: 7)
Interest.create(name: 'Swimming & Water Sports', category_id: 7)
Interest.create(name: 'Hockey', category_id: 7)
Interest.create(name: 'Motorsports', category_id: 7)
Interest.create(name: 'Fighting & Martial Arts', category_id: 7)
Interest.create(name: 'Snow Sports', category_id: 7)
Interest.create(name: 'Rugby', category_id: 7)
Interest.create(name: 'Yoga', category_id: 7)
Interest.create(name: 'Exercise', category_id: 7)
Interest.create(name: 'Softball', category_id: 7)
Interest.create(name: 'Wrestling', category_id: 7)
Interest.create(name: 'Lacrosse', category_id: 7)
Interest.create(name: 'Cheer', category_id: 7)
Interest.create(name: 'Camps', category_id: 7)
Interest.create(name: 'Weightlifting', category_id: 7)
Interest.create(name: 'Track & Field', category_id: 7)
Interest.create(name: 'Other', category_id: 7)

# Now lets create some interests for the health category
Interest.create(name: 'Personal Health', category_id: 8)
Interest.create(name: 'Mental Health', category_id: 8)
Interest.create(name: 'Medical', category_id: 8)
Interest.create(name: 'Spa', category_id: 8)
Interest.create(name: 'Yoga', category_id: 8)
Interest.create(name: 'Other', category_id: 8)

# Now lets create some interests for the Science & Tech category
Interest.create(name: 'Medicine', category_id: 9)
Interest.create(name: 'Science', category_id: 9)
Interest.create(name: 'Biotech', category_id: 9)
Interest.create(name: 'High Tech', category_id: 9)
Interest.create(name: 'Mobile', category_id: 9)
Interest.create(name: 'Social Media', category_id: 9)
Interest.create(name: 'Robotics', category_id: 9)
Interest.create(name: 'Other', category_id: 9)

# Now lets create some interests for the Travel & Outdoor category
Interest.create(name: 'Hiking', category_id: 10)
Interest.create(name: 'Rafting', category_id: 10)
Interest.create(name: 'Kayaking', category_id: 10)
Interest.create(name: 'Canoeing', category_id: 10)
Interest.create(name: 'Climbing', category_id: 10)
Interest.create(name: 'Travel', category_id: 10)
Interest.create(name: 'Other', category_id: 10)

# Now lets create some interests for the Charity & Causes category
Interest.create(name: 'Animal Welfare', category_id: 11)
Interest.create(name: 'Environment', category_id: 11)
Interest.create(name: 'Healthcare', category_id: 11)
Interest.create(name: 'Human Rights', category_id: 11)
Interest.create(name: 'International Aid', category_id: 11)
Interest.create(name: 'Poverty', category_id: 11)
Interest.create(name: 'Disaster Relief', category_id: 11)
Interest.create(name: 'Education', category_id: 11)
Interest.create(name: 'Other', category_id: 11)

# Now lets create some interests for the Spirituality category
Interest.create(name: 'Christianity', category_id: 12)
Interest.create(name: 'Judaism', category_id: 12)
Interest.create(name: 'Islam', category_id: 12)
Interest.create(name: 'Mormonism', category_id: 12)
Interest.create(name: 'Buddhism', category_id: 12)
Interest.create(name: 'Sikhism', category_id: 12)
Interest.create(name: 'Eastern Religion', category_id: 12)
Interest.create(name: 'Mysticism and Occult', category_id: 12)
Interest.create(name: 'New Age', category_id: 12)
Interest.create(name: 'Atheism', category_id: 12)
Interest.create(name: 'Agnosticism', category_id: 12)
Interest.create(name: 'Unaffiliated', category_id: 12)
Interest.create(name: 'Hinduism', category_id: 12)
Interest.create(name: 'Folk Religions', category_id: 12)
Interest.create(name: 'Shintoism', category_id: 12)
Interest.create(name: 'Other', category_id: 12)

# Now lets create some interests for the Family & Education category
Interest.create(name: 'Education', category_id: 13)
Interest.create(name: 'Alumni', category_id: 13)
Interest.create(name: 'Parenting', category_id: 13)
Interest.create(name: 'Baby', category_id: 13)
Interest.create(name: 'Children & Youth', category_id: 13)
Interest.create(name: 'Parents Association', category_id: 13)
Interest.create(name: 'Reunion', category_id: 13)
Interest.create(name: 'Senior Citizen', category_id: 13)
Interest.create(name: 'Other', category_id: 13)

# Now lets create some interests for the Holiday category
Interest.create(name: 'St Patricks Day', category_id: 14)
Interest.create(name: 'Easter', category_id: 14)
Interest.create(name: 'Independence Day', category_id: 14)
Interest.create(name: 'Halloween/Haunt', category_id: 14)
Interest.create(name: 'Thanksgiving', category_id: 14)
Interest.create(name: 'Christmas', category_id: 14)
Interest.create(name: 'Channukah', category_id: 14)
Interest.create(name: 'Fall Events', category_id: 14)
Interest.create(name: 'New Years Eve', category_id: 14)
Interest.create(name: 'Other', category_id: 14)

# Now lets create some interests for the Government category
Interest.create(name: 'Republican Party', category_id: 15)
Interest.create(name: 'Democratic Party', category_id: 15)
Interest.create(name: 'Other Party', category_id: 15)
Interest.create(name: 'Non-partisan', category_id: 15)
Interest.create(name: 'Federal Government', category_id: 15)
Interest.create(name: 'State Government', category_id: 15)
Interest.create(name: 'County/Municipal Government', category_id: 15)
Interest.create(name: 'Military', category_id: 15)
Interest.create(name: 'International Affairs', category_id: 15)
Interest.create(name: 'National Security', category_id: 15)
Interest.create(name: 'Other', category_id: 15)

# Now lets create some interests for the Fashion category
Interest.create(name: 'Fashion', category_id: 16)
Interest.create(name: 'Accessories', category_id: 16)
Interest.create(name: 'Bridal', category_id: 16)
Interest.create(name: 'Beauty', category_id: 16)
Interest.create(name: 'Other', category_id: 16)

# Now lets create some interests for the Home & Lifestyle category
Interest.create(name: 'Dating', category_id: 17)
Interest.create(name: 'Pets & Animals', category_id: 17)
Interest.create(name: 'Home & Garden', category_id: 17)
Interest.create(name: 'Other', category_id: 17)

# Now lets create some interests for the Auto, Boat & Air category
Interest.create(name: 'Auto', category_id: 18)
Interest.create(name: 'Motorcycle/ATV', category_id: 18)
Interest.create(name: 'Boat', category_id: 18)
Interest.create(name: 'Air', category_id: 18)
Interest.create(name: 'Other', category_id: 18)

# Now lets create some interests for the Hobbies category
Interest.create(name: 'Anime/Comics', category_id: 19)
Interest.create(name: 'Gaming', category_id: 19)
Interest.create(name: 'DIY', category_id: 19)
Interest.create(name: 'Photography', category_id: 19)
Interest.create(name: 'Knitting', category_id: 19)
Interest.create(name: 'Books', category_id: 19)
Interest.create(name: 'Adult', category_id: 19)
Interest.create(name: 'Drawing & Painting', category_id: 19)
Interest.create(name: 'Other', category_id: 19)

# Now lets create some interests for the School Activities category
Interest.create(name: 'Dinner', category_id: 20)
Interest.create(name: 'Fund Raiser', category_id: 20)
Interest.create(name: 'Raffle', category_id: 20)
Interest.create(name: 'After School Care', category_id: 20)
Interest.create(name: 'Parking', category_id: 20)
Interest.create(name: 'Public Speaker', category_id: 20)
